//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LibManagement.EF
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class LibraryEntities : DbContext
    {
        public LibraryEntities()
            : base("name=LibraryEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<tbl_Books> tbl_Books { get; set; }
        public DbSet<tbl_Borrow> tbl_Borrow { get; set; }
        public DbSet<tbl_Login> tbl_Login { get; set; }
        public DbSet<tbl_Question> tbl_Question { get; set; }
        public DbSet<tbl_Register> tbl_Register { get; set; }
        public DbSet<tbl_Type> tbl_Type { get; set; }
        public DbSet<tbl_User> tbl_User { get; set; }
    }
}
