//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LibManagement.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Borrow
    {
        public int Id { get; set; }
        public Nullable<int> BookId { get; set; }
        public Nullable<int> BorrowerId { get; set; }
        public string BorrowDate { get; set; }
        public string ReturnDate { get; set; }
    
        public virtual tbl_Books tbl_Books { get; set; }
        public virtual tbl_User tbl_User { get; set; }
    }
}
